##Question 2

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense

In [2]:
l = 0.2
h = 0.1
E = pow(10,7)

In [3]:
# defining total deflection
def total_deflection (F,V,E,l,h):
  I = 1/3*h*l*l*l
  delta_x = (0.1*V*V*l*l*l*l/(8*E*I)) + (F*l*l*l/(3*E*I))
  return delta_x

In [4]:
# generating training data
n_sample_train = 5000
F_train = np.random.uniform(low=1, high=10000, size=n_sample_train)
V_train = np.random.uniform(low=10, high=5000, size=n_sample_train)
X_train = np.empty((n_sample_train,2))
for i in range(n_sample_train):
  X_train[i][0] = F_train[i]
  X_train[i][1] = V_train[i]

y_train = total_deflection(F_train,V_train,E,l,h)
Y_train = np.empty((n_sample_train))
for i in range(n_sample_train):
  if 0.05<=y_train[i]<0.3:
    Y_train[i] = 1
  else : Y_train[i] = 0


In [5]:
Y_train

array([1., 1., 1., ..., 0., 0., 1.])

In [6]:
X_train

array([[1621.83852341, 4977.58947432],
       [4814.14892077, 2764.58175475],
       [ 480.12224885, 4287.12866217],
       ...,
       [5887.35878526, 2156.80037799],
       [5460.39642768, 2223.98380544],
       [7199.24710534, 4657.99958511]])

In [7]:
V_train

array([4977.58947432, 2764.58175475, 4287.12866217, ..., 2156.80037799,
       2223.98380544, 4657.99958511])

In [ ]:
F_train

In [ ]:
y_train

In [ ]:
Y_train

In [8]:
zeroes = 0
ones = 0
for i in range(n_sample_train):
  if Y_train[i] == 0: zeroes = zeroes+1
  else : ones = ones+1

print(zeroes,ones)

2438 2562


In [10]:
# generating validation data
n_sample_valid = 1500
F_valid = np.random.uniform(low=1, high=9000, size=n_sample_valid)
V_valid = np.random.uniform(low=10, high=5000, size=n_sample_valid)
X_valid = np.empty((n_sample_valid,2))
for i in range(n_sample_valid):
  X_valid[i][0] = F_valid[i]
  X_valid[i][1] = V_valid[i]

y_valid = total_deflection(F_valid,V_valid,E,l,h)
Y_valid = np.empty((n_sample_valid))
for i in range(n_sample_valid):
  if 0.05<=y_valid[i]<0.3:
    Y_valid[i] = 1
  else : Y_valid[i] = 0


In [11]:
# generating testing data
n_sample_test = 1000
F_test = np.random.uniform(low=1, high=10000, size=n_sample_test)
V_test = np.random.uniform(low=10, high=5000, size=n_sample_test)
X_test = np.empty((n_sample_test,2))
for i in range(n_sample_test):
  X_test[i][0] = F_test[i]
  X_test[i][1] = V_test[i]

y_test = total_deflection(F_test,V_test,E,l,h)
Y_test = np.empty((n_sample_test))
for i in range(n_sample_test):
  if 0.05<=y_test[i]<0.3:
    Y_test[i] = 1
  else : Y_test[i] = 0


In [12]:
# Define the model architecture
model = Sequential()
model.add(Dense(32, input_dim=2, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(14, activation='relu'))
model.add(Dense(18, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [13]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])


In [14]:
# Train the model

history = model.fit(X_train, Y_train, epochs=200, batch_size=32, validation_data=(X_valid, Y_valid))


Epoch 1/200
157/157 [==============================] - 1s 3ms/step - loss: 2.7210 - binary_accuracy: 0.7316 - val_loss: 0.5946 - val_binary_accuracy: 0.7820
Epoch 2/200
157/157 [==============================] - 0s 2ms/step - loss: 0.9032 - binary_accuracy: 0.7566 - val_loss: 0.5454 - val_binary_accuracy: 0.7740
Epoch 3/200
157/157 [==============================] - 0s 2ms/step - loss: 0.6441 - binary_accuracy: 0.7754 - val_loss: 0.6578 - val_binary_accuracy: 0.7693
Epoch 4/200
157/157 [==============================] - 0s 3ms/step - loss: 0.5233 - binary_accuracy: 0.7882 - val_loss: 0.4552 - val_binary_accuracy: 0.8107
Epoch 5/200
157/157 [==============================] - 0s 2ms/step - loss: 0.6879 - binary_accuracy: 0.7982 - val_loss: 0.3393 - val_binary_accuracy: 0.8420
Epoch 6/200
157/157 [==============================] - 0s 2ms/step - loss: 0.5142 - binary_accuracy: 0.8110 - val_loss: 0.4028 - val_binary_accuracy: 0.8207
Epoch 7/200
157/157 [==============================] - 0s 

In [15]:
# Evaluate the model on the testing data
loss, binary_accuracy = model.evaluate(X_test, Y_test)
print('Test loss:', loss)
print('Test accuracy:', binary_accuracy)

32/32 [==============================] - 0s 1ms/step - loss: 0.0234 - binary_accuracy: 0.9970
Test loss: 0.023355232551693916
Test accuracy: 0.996999979019165


In [ ]:
X_train

In [ ]:
y_train

In [16]:
model.predict([[7079.83388333, 3036.26026819]])#,[866.74427827, 2736.73497739]])

1/1 [==============================] - 0s 111ms/step


array([[0.9998701]], dtype=float32)

In [ ]:
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer()

In [17]:
import pickle

pickle.dump(model, open('model.pkl', 'wb')) #Saving the model
model_pkd = pickle.load(open('model.pkl', 'rb')) #To load saved model from local directory

In [18]:
model_pkd
loss_pkd, binary_accuracy_pkd = model_pkd.evaluate(X_test, Y_test)
print('Test loss:', loss_pkd)
print('Test accuracy:', binary_accuracy_pkd)

32/32 [==============================] - 0s 2ms/step - loss: 0.0234 - binary_accuracy: 0.9970
Test loss: 0.023355232551693916
Test accuracy: 0.996999979019165


In [ ]:
type(X_test)

In [19]:
arr = np.array([[53, 25]])

In [20]:
model_pkd.predict(arr)

1/1 [==============================] - 2s 2s/step


array([[6.718737e-10]], dtype=float32)

In [ ]:
# Get training and test loss histories
training_loss = history.history['loss']
valid_loss = history.history['val_loss']

# Create count of the number of epochs
epoch_count = range(1, len(training_loss) + 1)

# Visualize loss history
plt.plot(epoch_count, training_loss, 'r--')
plt.plot(epoch_count, valid_loss, 'b-')
plt.legend(['Training loss', 'Validation loss'])
plt.title('Training and Validation loss vs Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.show();

In [ ]:
# Generate confusion matrix
y_pred = (model.predict(X_test) > 0.5).astype("int32")
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
cm = confusion_matrix(Y_test, y_pred)
sns.heatmap(cm,annot=True)


In [ ]:
y_pred = np.squeeze(model.predict(X_test)>=0.5).astype(int)
cm = confusion_matrix(Y_test, y_pred, labels=[0,1])
#clr = classification_report(Y_test, y_pred, labels=[0,1], target_names = ["Not Working", "Working"])

plt.figure(figsize = (6,6))
sns.heatmap(cm, annot=True, fmt='g', vmin = 0, cmap = 'Blues', cbar = False)
plt.xticks(ticks = [0.5,1.5], labels=["Not working", "Working"])
plt.yticks(ticks = [0.5,1.5], labels=["Not Working", "Working"])
plt.xlabel('predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')

plt.show()
#print("Classification Report:\n------------------\n", clr)